### ISSUE TITLE
Chapel Hill police reports

### ISSUE THREAD

**Issue by tobiasmcnulty** [OpenData-NC/openrural-nc#13]
http://p2c.chpd.us/Summary.aspx

Winston-Salem uses the same system but doens't have arrest reports

**Comment by tobiasmcnulty** [comment]
Ryan noted that the address on reports may be the police station

**Comment by tobiasmcnulty** [comment]
Carrboro does not have data online

**Comment by tobiasmcnulty** [comment]
I put up an initial scraper for this data here:

https://scraperwiki.com/scrapers/chapel_hill_police_reports/

I'm having trouble getting mechanize to pull down any page beyond the first one (note the commented out code near the bottom)

**Comment by copelco** [comment]
From our 12/14 meeting notes: Fix unique key issues for crime data

**Comment by copelco** [comment]
I'm closing this in favor of a more specific issue #31
