### ISSUE TITLE
NC Secretary of State corporation filings

### ISSUE THREAD

**Issue by tobiasmcnulty** [OpenData-NC/openrural-nc#16]
http://www.secretary.state.nc.us/Corporations/SearchChgs.aspx

**Comment by copelco** [comment]
I created a working importer here:

https://github.com/openrural/openrural-nc/blob/master/openrural/retrieval/orange_corp_filings.py

The script still needs the scraping aspect yet, currently you download the file manually for import.

**Comment by copelco** [comment]
I updated the scraper to cast DateFormed to a datetime (for proper sorting) and SOSID to an int.

**Comment by copelco** [comment]
The scraper is now scheduled to run every 3 days. Closing this as finished.
